### ISSUE TITLE
Support for discrete actions?

### ISSUE THREAD

**Issue by hai-h-nguyen** [ku2482/gail-airl-ppo.pytorch#4]
Does this codebase support discrete action spaces?

**Comment by toshikwa** [comment]
Discrete actions are not supported.

**Comment by prasuchit** [comment]
@toshikwa @hai-h-nguyen I know it's been a long time, but I just added support for discrete actions. It's available [here](https://github.com/prasuchit/gail-airl-ppo.pytorch/tree/master).
