### ISSUE TITLE
about reparametrize

### ISSUE THREAD

**Issue by ZhenZhuHuang** [ku2482/gail-airl-ppo.pytorch#7]
````
def calculate_log_pi(log_stds, noises, actions):
    gaussian_log_probs = (-0.5 * noises.pow(2) - log_stds).sum(
        dim=-1, keepdim=True) - 0.5 * math.log(2 * math.pi) * log_stds.size(-1)

    return gaussian_log_probs - torch.log(
        1 - actions.pow(2) + 1e-6).sum(dim=-1, keepdim=True)
```


```
def reparameterize(means, log_stds):
    noises = torch.randn_like(means)
    us = means + noises * log_stds.exp()
    actions = torch.tanh(us)
    return actions, calculate_log_pi(log_stds, noises, actions)`
```
Hello, I would like to ask why the calculate_log_pi function calculates the logpi this way. I can't find the algorithm, okay?

**Comment by toshikwa** [comment]
The reason why I do `us = means + noises * log_stds.exp()` is called "reparametrization trick".
Try calculating the log probability of gaussian distribution using `noises[i] = N(\mu=0, \sigma=I)`, you'll see.

I avoided using `torch.distributions.Normal().log_prob()` in order to reduce calculation.

Does it make sense?

**Comment by ZhenZhuHuang** [comment]
What I don't understand is that the calculation formula of normal. Log_prob seems to be different from your code, so it is confused. Thank you for your answer, Sir.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ku2482/gail-airl-ppo.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ku2482/gail-airl-ppo.pytorch] about reparametrize (Issue #7)





 
The reason why I do us = means + noises * log_stds.exp() is called "reparametrization trick".
 Try calculating the log probability of gaussian distribution using noises[i] = N(\mu=0, \sigma=I), you'll see.
 
I avoided using torch.distributions.Normal().log_prob() in order to reduce calculation.
 
Does it make sense?

**Comment by toshikwa** [comment]
`Normal(means, stds).log_prob(means + noises * stds)` equals to `Normal(0, stds).log_prob(noises * stds)`.
So, I can reduce unnecessary calculation.

**Comment by ZhenZhuHuang** [comment]
Okay, I think I get it. One last question, does GAIL based on PPO and SAC have any relevant papers or blogs? Thank you for your help, Sir.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ku2482/gail-airl-ppo.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ku2482/gail-airl-ppo.pytorch] about reparametrize (Issue #7)





 
Normal(means, stds).log_prob(means + noises * stds) equals to Normal(0, stds).log_prob(noises * stds).
 So, I can reduce unnecessary calculation.

**Comment by toshikwa** [comment]
I'm sorry, but I don't remember...

**Comment by ZhenZhuHuang** [comment]
Well, thank you for your patience!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ku2482/gail-airl-ppo.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ku2482/gail-airl-ppo.pytorch] about reparametrize (Issue #7)





 
I'm sorry, but I don't remember...
