### ISSUE TITLE
About disc's output

### ISSUE THREAD

**Issue by nicholas0717** [ku2482/gail-airl-ppo.pytorch#8]
Hi @toshikwa 

I'm puzzled with your annotation in `update_disc()`. You said output of discriminator is (-inf, inf), not [0, 1]. Should the output of disc be (-1, 1) when `hidden_activation` of the disc is `nn.Tanh()`. I don't know whether I understand it incorrectly.

Looking forward to your reply. Thanks!

**Comment by toshikwa** [comment]
Hi @nicholas0717 

Output is (-inf, inf) if you don't specify `output_activation`.
https://github.com/toshikwa/gail-airl-ppo.pytorch/blob/master/gail_airl_ppo/network/utils.py#L15-L16

Does it make sense?

**Comment by nicholas0717** [comment]
Thank you! I get it. I didn't read the utils.py carefully.

Appreciate your reply!
